[versions]
androidx-lifecycle = "2.9.4"
composeHotReload = "1.0.0-beta06"
composeMultiplatform = "1.9.0"
junit = "4.13.2"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-serialization-plugin = "2.2.20"
material-expressive = "1.9.0-alpha04"
splitpane = "1.10.0-alpha01"
coil-compose = "3.3.0"
koin = "4.1.1"
compottie = "2.0.0"
voyager = "1.1.0-beta02"
ktor = "3.2.3"
exposed = "0.61.0"
logback = "1.5.13"
sqldelight = "2.1.0"
faker = "2.0.0-rc.11"
h2 = "2.3.232"
identityJvm = "202411.1"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
material-expressive = { module = "org.jetbrains.compose.material3:material3", version.ref = "material-expressive" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }

#!! Compose Desktop
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
splitpane-desktop = { module = "org.jetbrains.compose.components:components-splitpane-desktop", version.ref = "splitpane" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-compose" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil-compose" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil-compose" }
# Koin
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Compottie
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
# Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
voyager = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
#Faker
faker = { module = "io.github.serpro69:kotlin-faker", version.ref = "faker" }

#!! KTOR SERVER
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serverContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serverStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
ktor-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
ktor-exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
ktor-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
ktor-h2Database = { module = "com.h2database:h2", version.ref = "h2" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.3" }
mindrot-jbcrypt = { module = "org.mindrot:jbcrypt", version = "0.4" }

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization-plugin" }